# .github/workflows/test.yml
name: Run Tests

on:
  pull_request:
    branches: [test]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run User Flow Tests Only
        run: npx jest src/__tests__/flows
